### ISSUE TITLE
Cannot install in my Mac... but it is deeper problem with the repo...

### ISSUE THREAD

**Issue by bonetblai** [brrcrites/graph-coloring#36]
Dear,

I'm interested in using your software for a research related problem involving graph coloring. However, when I tried to install it in my Mac with the provided instructions "cmake . ; make" the following happens:

1. Cmake complains about gflags/ and googletest/ folder as they are empty. Hence, I commented out the corresponding two ADD_SUBDIRECTORY lines in ./CMakeLists.txt
2. After this, cmake succeeds but now make fails. The source main.cpp includes gflags/gflags.h but that folder is empty, and main.cpp won't compile if the corresponding include directive is commented out.

Please, advice...

Thanks!

Blai Bonet

**Comment by brrcrites** [comment]
Hello @bonetblai,

Since my response is almost a year late I'm going to generally assume you've moved on from attempting to get this to work, but it sounds like you've pulled the repository without the submodules (thus the `gflags/` and `googleteset/` directories being empty). You can try running `git submodule update --init` in the repo and see if that fixes your issue (and re-enable the `ADD_SUBDIRECTORY` lines back to `CMakeLists.txt`)

-Brian
